# Generated by Django 2.2.6 on 2019-10-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_up',
            old_name='date',
            new_name='date_fillup',
        ),
    ]
