# Generated by Django 2.2.6 on 2019-10-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20191023_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='last_update',
            old_name='date',
            new_name='date_log',
        ),
    ]
