# Generated by Django 2.2.6 on 2019-10-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_start_date',
            name='version_log',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
