# Generated by Django 2.2.6 on 2019-10-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_start_date_version_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_start_date',
            name='user_superior',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
