# Generated by Django 2.2.6 on 2019-10-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_start_date_user_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_start_date',
            name='temp_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
