# Generated by Django 2.2.6 on 2019-10-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_start_date_temp_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_start_date',
            old_name='temp_row',
            new_name='version_temp',
        ),
    ]
