# Generated by Django 2.2.6 on 2019-10-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191026_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_start_date',
            name='version_log_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_start_date',
            name='version_temp_end',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
